/**
 * Knowledge base retrieval for the DAR Hypotheken chatbot.
 * Loads the pre-built chunks (generated by scripts/import-knowledge-base.mjs
 * from the Sharif Q&A xlsx) and retrieves the most relevant ones via
 * keyword-overlap scoring.
 */

import fs from "fs";
import path from "path";

export interface KnowledgeFollowup {
  q: string;
  a: string;
}

export interface KnowledgeChunk {
  id: string;
  category: string;
  title: string;
  question: string;
  content: string;
  followups: KnowledgeFollowup[];
  keywords: string[];
  source: string;
  reviewStatus: string;
}

// In-memory cache of loaded chunks per locale
const chunksCache = new Map<string, KnowledgeChunk[]>();

/**
 * Load knowledge chunks from disk. Caches in memory after first load.
 */
export function loadChunks(locale: "nl" | "en"): KnowledgeChunk[] {
  const cached = chunksCache.get(locale);
  if (cached) return cached;

  const filePath = path.join(
    process.cwd(),
    "src",
    "data",
    "knowledge",
    `chunks-${locale}.json`,
  );

  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    const chunks: KnowledgeChunk[] = JSON.parse(raw);
    chunksCache.set(locale, chunks);
    return chunks;
  } catch {
    console.warn(`Failed to load knowledge chunks for locale: ${locale}`);
    return [];
  }
}

/**
 * Tokenize into lowercase word set for comparison.
 */
function tokenize(text: string): Set<string> {
  return new Set(
    text
      .toLowerCase()
      .replace(/[^\p{L}\p{N}\s]/gu, " ")
      .split(/\s+/)
      .filter((w) => w.length > 2),
  );
}

/**
 * Return the number of query tokens that appear in the target text's tokens
 * (partial-substring aware, both directions).
 */
function overlapCount(queryTokens: Set<string>, targetText: string): number {
  const target = tokenize(targetText);
  let hits = 0;
  for (const q of queryTokens) {
    for (const t of target) {
      if (t.includes(q) || q.includes(t)) {
        hits++;
        break;
      }
    }
  }
  return hits;
}

/**
 * Score a chunk against the query. Higher-signal fields get higher weight:
 *   - main question text:  ×5  (users phrase their asks like the FAQ question)
 *   - follow-up questions: ×3  (same reasoning, but secondary)
 *   - keywords:            ×3  (auto-extracted, high signal)
 *   - title:               ×2
 *   - content body:        ×1
 */
function scoreChunk(query: string, chunk: KnowledgeChunk): number {
  const q = tokenize(query);
  if (q.size === 0) return 0;

  let score = 0;
  score += 5 * overlapCount(q, chunk.question ?? "");
  for (const fu of chunk.followups ?? []) {
    score += 3 * overlapCount(q, fu.q);
  }
  if (chunk.keywords?.length) {
    score += 3 * overlapCount(q, chunk.keywords.join(" "));
  }
  score += 2 * overlapCount(q, chunk.title ?? "");
  score += 1 * overlapCount(q, chunk.content ?? "");
  return score;
}

/**
 * Minimum score required for a chunk to be considered relevant.
 * Tuned so that a single random keyword match doesn't drag in unrelated
 * chunks. One main-question match (×5) clears it, as does one follow-up
 * match (×3). Pure keyword overlap needs at least two token hits.
 */
const MIN_RELEVANCE_SCORE = 3;

/**
 * Retrieve the most relevant knowledge chunks for a query.
 *
 * Returns [] (empty) when nothing clears MIN_RELEVANCE_SCORE — the system
 * prompt then instructs the model to honestly say it lacks that
 * information rather than hallucinate from general knowledge.
 *
 * Default cap of 3 chunks because each one now carries main + follow-up
 * Q/A pairs (~1.2k chars) and Haiku has a 500-token output budget.
 */
export function retrieveRelevantChunks(
  query: string,
  locale: "nl" | "en",
  maxChunks: number = 3,
): KnowledgeChunk[] {
  const chunks = loadChunks(locale);

  const scored = chunks
    .map((chunk) => ({ chunk, score: scoreChunk(query, chunk) }))
    .filter(({ score }) => score >= MIN_RELEVANCE_SCORE)
    .sort((a, b) => b.score - a.score)
    .slice(0, maxChunks);

  // Intentionally NO fallback to "first few chunks" — we'd rather the
  // assistant say "I don't have that information" than invent an answer
  // from unrelated context.
  return scored.map(({ chunk }) => chunk);
}

/**
 * Format retrieved chunks into a context string for the system prompt.
 * Includes category tag + review-status warning so the model can soften
 * claims on policies that Dar is still finalising.
 */
export function buildContext(chunks: KnowledgeChunk[]): string {
  if (chunks.length === 0) return "No relevant information available.";

  return chunks
    .map((chunk) => {
      const header = `[${chunk.id} · ${chunk.category}] ${chunk.title}`;
      const caveat =
        chunk.reviewStatus && chunk.reviewStatus !== "Ready"
          ? `\n(Review status: ${chunk.reviewStatus} — caveat the answer.)`
          : "";
      return `--- ${header} ---${caveat}\n${chunk.content}`;
    })
    .join("\n\n");
}
